name: Test and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm install

      - name: Build
        run: npm run build --if-present

      - name: eslint & tests
        run: npm run lint && npm run only-test

  visual_regression_test:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 18.x.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x.x

    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Run visual regression tests
      run: npm run loki:ci

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: visual_regression_tests_difference
        path: .loki/difference/**

  user_journey_test_local:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x
      - name: create env file
        run: |
          touch .env
          echo VITE_MAPS_API_KEY =${{ secrets.DEV_MAPS_API_KEY }} >> .env

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Cypress
        run: ./node_modules/cypress/bin/cypress install

      - name: Run User Journey tests
        run: npm run ci:cypress-run

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: user_journey_test_local_screenshot
          path: cypress/screenshots/**

  outdated_deps:
    needs: [ user_journey_test_local, visual_regression_test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Show outdated deps
        run: npm outdated || true
      - name: Check outdated deps limit
        run: test $(npm outdated | wc -l) -lt "10"

  build_and_deploy_dev:
    needs: [ user_journey_test_local, visual_regression_test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: create env file
        run: |
          touch .env
          echo VITE_MAPS_API_KEY =${{ secrets.DEV_MAPS_API_KEY }} >> .env

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build --if-present

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P development
        env:
          FIREBASE_TOKEN: ${{ secrets.DEV_FIREBASE_TOKEN }}

  user_journey_test_dev:
    needs: build_and_deploy_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Cypress
        run: ./node_modules/cypress/bin/cypress install

      - name: Run User Journey tests
        run: CYPRESS_BASE_URL=https://compaz-dev.web.app npm run cypress:ci

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: user_journey_test_dev_screenshot
          path: cypress/screenshots/**

  build_and_deploy_prod:
    needs: [ user_journey_test_dev ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: create env file
        run: |
          touch .env
          echo VITE_MAPS_API_KEY =${{ secrets.MAPS_API_KEY }} >> .env

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build --if-present

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  user_journey_test_prod:
    needs: build_and_deploy_prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Cypress
        run: ./node_modules/cypress/bin/cypress install

      - name: Run User Journey tests
        run: CYPRESS_BASE_URL=https://compaz.app npm run cypress:ci

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: user_journey_test_prod_screenshot
          path: cypress/screenshots/**