name: Test and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Frontend eslint & tests
      run: npm ci && npm run build --if-present && npm run lint && npm run only_test

  visual_regression_test:
    needs: build_and_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci && npm run loki:ci

  user_journey_test:
    needs: build_and_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci && npm start
      - run: npm run cypress:ci

  outdated_deps:
    needs: [visual_regression_test, user_journey_test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm outdated || true
      - run: test $(npm outdated | wc -l) -lt "25"

  build_and_deploy:
    needs: [visual_regression_test, user_journey_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_MAPS_API_KEY =${{ secrets.MAPS_API_KEY }} >> .env
      - name: Frontend build
        run: npm ci && npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}